Add initial support for dump/restore based images

diff --git a/create b/create
--- a/create
+++ b/create
@@ -27,6 +27,8 @@ if [ "$IMAGE_TYPE" = "tarball" ] ; then
     IMAGE_FILE="${IMAGE_DIR}/${IMAGE_NAME}-${ARCH}.tar.gz"
 elif [ "$IMAGE_TYPE" = "qemu" ] ; then
     IMAGE_FILE="${IMAGE_DIR}/${IMAGE_NAME}-${ARCH}.img"
+elif [ "$IMAGE_TYPE" = "dump" ] ; then
+    IMAGE_FILE="${IMAGE_DIR}/${IMAGE_NAME}-${ARCH}-root.dump"
 fi
 
 if [ "$CDINSTALL" = "no" ] ; then
@@ -45,7 +47,7 @@ if [ "$CDINSTALL" = "no" ] ; then
 
     # If the image is tarball based, then we need to manually create the
     # volumes, filesystems, etc
-    if [ "${IMAGE_TYPE}" = "tarball" ] ; then
+    if [ "${IMAGE_TYPE}" = "tarball" -o "${IMAGE_TYPE}" = "dump" ] ; then
         # Create 3 partitions, /boot, swap, & /
         format_disk0 $blockdev
     elif [ "${IMAGE_TYPE}" = "qemu" ] ; then
@@ -64,7 +66,7 @@ if [ "$CDINSTALL" = "no" ] ; then
     fi
     CLEANUP+=("unmap_disk0 $blockdev")
 
-    if [ "${IMAGE_TYPE}" = "tarball" ] ; then
+    if [ "${IMAGE_TYPE}" = "tarball" -o "${IMAGE_TYPE}" = "dump" ] ; then
         mkfs_disk0 $boot_dev $root_dev $swap_dev
     fi
 
@@ -77,6 +79,15 @@ if [ "$CDINSTALL" = "no" ] ; then
     if [ "${IMAGE_TYPE}" = "tarball" ] ; then
         # unpack image
         tar pzxf $IMAGE_FILE -C $TARGET
+    elif [ "${IMAGE_TYPE}" = "dump" ] ; then
+        boot_dump="${IMAGE_FILE/root.dump/boot.dump}" 
+        root_dump="${IMAGE_FILE}"
+        if [ ! -f "$boot_dump" ] ; then
+          log_error "Can't find image file: $boot_dump"
+          exit 1
+        fi
+        ( cd ${TARGET}; restore -r -y -f ${root_dump} )
+        ( cd ${TARGET}/boot; restore -r -y -f ${boot_dump} )
     fi
 
     RUN_PARTS=`which run-parts`
