Ticket #219: Add NOMOUNT option to allow Windows install
Use included patch but extend to import, export, and rename scripts. For now
rename does nothing since we have no way of knowing what the image might be
(windows, linux, etc).

diff --git a/export b/export
--- a/export
+++ b/export
@@ -31,39 +31,47 @@ if [ ! -b $blockdev ]; then
     CLEANUP+=("$LOSETUP -d $blockdev")
 fi
 
-filesystem_dev=$(map_disk0 $blockdev)
-CLEANUP+=("unmap_disk0 $blockdev")
-root_dev=$(map_partition $filesystem_dev root)
-boot_dev=$(map_partition $filesystem_dev boot)
-
+if [ ! "${NOMOUNT}" = "yes" ] ; then
+    filesystem_dev=$(map_disk0 $blockdev)
+    CLEANUP+=("unmap_disk0 $blockdev")
+    root_dev=$(map_partition $filesystem_dev root)
+    boot_dev=$(map_partition $filesystem_dev boot)
+fi
 
 TARGET=`mktemp -d` || exit 1
 CLEANUP+=("rmdir $TARGET")
 
-vol_type_root="$($VOL_TYPE $root_dev)"
-if [ -n "${boot_dev}" ] ; then
-    vol_type_boot="$($VOL_TYPE $boot_dev)"
-fi
-
-for fs in boot root ; do
-    # use indirect reference to make the variables dynamic
-    dev="$(eval "echo \${$(echo ${fs}_dev)"})"
-    vol_type="$(eval echo \$vol_type_${fs})"
-    if [ -z "$vol_type" -a -n "${dev}" ] ; then
-        log_error "Unable to find ${fs} filesystem type at ${dev}"
-        exit 1
+if [ "${NOMOUNT}" = "yes" ] ; then
+    # convert block device to qcow2 image to support OS's like Windows. Use
+    # qcow2 to conserve on space.
+    $QEMU_IMG convert $blockdev -O qcow2 ${TARGET}/disk.img
+    CLEANUP+=("rm ${TARGET}/disk.img")
+else
+    vol_type_root="$($VOL_TYPE $root_dev)"
+    if [ -n "${boot_dev}" ] ; then
+        vol_type_boot="$($VOL_TYPE $boot_dev)"
     fi
-    if [ -n "${dev}" ] ; then
-        if [ "$vol_type" = "ext3" -o "$vol_type" = "ext2" \
-                -o "$vol_type" = "ext4" ] ; then
-            $DUMP -0 -q -z9 -f ${TARGET}/${fs}.dump $dev
-            CLEANUP+=("rm ${TARGET}/${fs}.dump")
-        else
-            log_error "${fs} is not a supported filesystem. Please use ext{2,3,4}"
+
+    for fs in boot root ; do
+        # use indirect reference to make the variables dynamic
+        dev="$(eval "echo \${$(echo ${fs}_dev)"})"
+        vol_type="$(eval echo \$vol_type_${fs})"
+        if [ -z "$vol_type" -a -n "${dev}" ] ; then
+            log_error "Unable to find ${fs} filesystem type at ${dev}"
             exit 1
         fi
-    fi
-done
+        if [ -n "${dev}" ] ; then
+            if [ "$vol_type" = "ext3" -o "$vol_type" = "ext2" \
+                    -o "$vol_type" = "ext4" ] ; then
+                $DUMP -0 -q -z9 -f ${TARGET}/${fs}.dump $dev
+                CLEANUP+=("rm ${TARGET}/${fs}.dump")
+            else
+                log_error "${fs} is not a supported filesystem. Please use ext{2,3,4}"
+                exit 1
+            fi
+        fi
+    done
+fi
 
 ( cd $TARGET ; tar -cf - . )
 
